name: reseg-pytorch
channels:
- soumith
- defaults
dependencies:
- certifi=2016.2.28=py27_0
- cffi=1.10.0=py27_0
- cudatoolkit=8.0=3
- cudnn=6.0.21=cuda8.0_0
- freetype=2.5.5=2
- jbig=2.1=0
- jpeg=8d=2
- lcms=1.19=0
- libffi=3.2.1=1
- libgcc=5.2.0=0
- libgfortran=3.0.0=1
- libpng=1.6.30=1
- libtiff=4.0.6=2
- mkl=2017.0.3=0
- nccl=1.3.4=cuda8.0_1
- numpy=1.13.1=py27_0
- openssl=1.0.2l=0
- pil=1.1.7=py27_2
- pillow=3.4.2=py27_0
- pip=9.0.1=py27_1
- pycparser=2.18=py27_0
- python=2.7.13=0
- readline=6.2=2
- scipy=0.19.1=np113py27_0
- setuptools=36.4.0=py27_1
- six=1.10.0=py27_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py27_0
- xz=5.2.3=0
- zlib=1.2.11=0
- pytorch=0.2.0=py27ha262b23_4cu75
- pip:
  - backports.shutil-get-terminal-size==1.0.0
  - convertdate==2.1.1
  - dateparser==0.6.0
  - decorator==4.1.2
  - enum34==1.1.6
  - ephem==3.7.6.0
  - ipython==5.5.0
  - ipython-genutils==0.2.0
  - iso3166==0.8
  - lmdb==0.93
  - olefile==0.44
  - pathlib==1.0.1
  - pathlib2==2.3.0
  - pexpect==4.3.1
  - pickleshare==0.7.4
  - prompt-toolkit==1.0.15
  - ptyprocess==0.5.2
  - pygments==2.2.0
  - pylibdmtx==0.1.7
  - python-dateutil==2.6.1
  - pytz==2017.2
  - pyyaml==3.12
  - regex==2017.7.28
  - ruamel.ordereddict==0.4.13
  - ruamel.yaml==0.15.26
  - scandir==1.6
  - simplegeneric==0.8.1
  - torch==0.2.0.post4
  - traitlets==4.3.2
  - tzlocal==1.4
  - umalqurra==0.2
  - wcwidth==0.1.7
  - xlrd==1.0.0
  - torchvision==0.2.0
prefix: /home/jcmaxwell/Libraries/anaconda2/envs/reseg-pytorch

